* Difficulty: 1
** Title: First Impressions
*** Truth: Describe the first physical trait you noticed of every other player.
*** Dare: Put on a blindfold.  The other players choose a body part and you have to identify them by feeling that body part.
*** Tags: contact
** Title: Dance Break
*** Truth: What dance move have you always wanted to be able to do, but have been to afraid to try?
*** Dare: Have another player name a dance move.  Attempt to do that move while listening to Rick Astley.
*** Tags: dancing,internet
** Title: Moonlight Serenade
*** Truth: What song makes you feel most romantic?  Why?
*** Dare: Choose another player and sing them the chorus to a romantic song.
*** Tags: exhibitionism
** Title: Break a Sweat
*** Truth: What is the most embarassing excercise story you have?  
*** Dare: Do either 30 pushups, 50 situps or 10 pullups.
*** Tags: athletic
* Difficulty: 2
** Title: Come Into My Orafice
*** Truth: What is the most unsual thing you've ever had lodged into an orafice?
*** Dare: Have each other player choose one item.  You must insert each one into an orafice for 5 seconds.
*** Tags: body fluids,contact
** Title: Who Smelt It
*** Truth: Describe a time when you passed gas and blamed it on someone else.
*** Dare: Choose between farting or smelling each other player's armpit.
*** Tags: body fluids
** Title: Some Like It Hot
*** Truth: What is the most memorable thing you have ever tasted?  Would you taste it again?
*** Dare: Find the spiciest thing in the immediate area (preferably the kitchen).  Hold it in your mouth for 5 seconds.
** Title: Follow the Money
*** Truth: What is the smallest amount of money someone would have to offer you to make you pose naked?
*** Dare: Take all of the cash you have on you (Up to $20) and put it out on the sidewalk for the duration of the game.
* Difficulty: 3
** Title: Tickle Me (TM)
*** Truth: What is your most ticklish spot?
*** Dare: Close your eyes and let each player have a 5 second attempt to make you laugh by tickling you.
*** Tags: contact
** Title: Kill All Humans
*** Truth: What is the most frustrating or annoying thing you've noticed about another player?
*** Dare: Poke another player in the belly until they make you stop.
*** Tags: contact
** Title: Voice of the People
*** Truth: If you could make one proclamation and everyone had to follow it for 1 day, what would it be?
*** Dare: Pass around a piece of paper.  Each person gets to write one word on the paper.  When the paper gets back to you, you have to shout it out the nearest window.
*** Tags: public
** Title: My Virgin Ears
*** Truth: What was the first story you heard about sex?
*** Dare: Have every player contribute a sexual term.  Look each one up in the UrbanDictionary.com and read it aloud.
*** Tags: internet,mature content
* Difficulty: 4
** Title: Battle of the Bands
*** Truth: What is the sexiest instrument?  Why is it sexy to you?
*** Dare: Have the other players hum a song whilst you play either Air Guitar, Air Drums or Air Upright Jazz Bass.
*** Tags: dancing
** Title: What They Don't Know
*** Truth: Name at least 3 misconceptions your parents have about how pure you are.
*** Dare: Send an email to your parents describing on thing you lied to them about that they don't yet know.
*** Tags: internet
** Title: Crush Cakes
*** Truth: What was the last crush you had that you never told anyone about?  What do yo wish you could have done with your crush?
*** Dare: Find someone in the room that you've secretly admired.  Go up and whisper what you admired to them.
*** Tags: public
** Title: What's the Story Morning Glory?
*** Dare: Ask the other players for a line.  Either in person or by telephone, you must use the line to attempt to get a date for tonight.
*** Truth: If you could be on a date tonight with anyone who you have actually met, who would it be?
* Difficulty: 5
** Title: Raspberries
*** Truth: What part of you body do you most enjoy having kissed, caressed or fondled?
*** Dare: Blow a raspberry on someone else's stomach.
*** Tags: contact
** Title: Another One Bites the Dust
*** Truth: What is the most disgusting thing you've ever pretended to like?
*** Dare: Each player gets to put one bite of food in a bowl.  You must eat them all simultaneously.
*** Tags: contact
** Title: Money Where Your Mouth Is
*** Truth: If you could change three things about your school/workplace, what would you change and why?
*** Dare: Write a letter to someone who has authority over you explaining one thing you'd change about the way they do things.
** Title: Can't Stop The Signal
*** Truth: Describe the last gossip you spread about someone else.
*** Dare: Open your email and do a search for each player's name.  Show only the results, not the detail.

*** Tags: internet
* Difficulty: 6
** Title: Wet Your Appetite
*** Truth: Describe the most revealing article of clothing you've worn in public.
*** Dare: Moisten one article of clothing and wear it for the duration of the game.

*** Tags: exhibitionism,messy,mature content
** Title: Auto Erotica
*** Dare: Go out to the nearest non-alarmed automobile and pretend to copulate with it for 10 seconds.
*** Truth: What was the most sexual thing you've done in a car?  With whom?
*** Tags: mature content,public
** Title: Why Do Birds Suddenly Appear
*** Truth: When did you most recently have the desire to flip someone the bird?  Did you?  Would you still like to?
*** Dare: Take a picture of you flipping the bird with a digital camera.  Choose another player who will send it to someone of their choice.
*** Tags: photo
** Title: Something Borrowed, Something Blue
*** Truth: What item from someone else do you keep close to you to remind you of them?
*** Dare: Have each player donate something and carry it in an undergarment for the remainder of the game.  Return it afterwards.
*** Tags: mature content,exhibitionism
* Difficulty: 7
** Title:Wee Bit Nipply
*** Truth: What is the genital feature you are the most self-conscious about?  Why?
*** Dare: Take an ice cube and rub it on a sensitive genital area for 30 seconds.  Feel free to meep.
*** Tags: mature content,exhibitionism
** Title: Namaste
*** Dare: Attempt 4 yoga positions while everyone watches.
*** Truth: What is the most complex sexual position you've ever attempted.
*** Tags: mature content
** Title: Kill Me Now
*** Truth: If you knew you were going to die today, what would you tell each player?
*** Dare: Give each player a farewell kiss.
*** Tags: contact,body fluids
** Title: Keep It Under Your Hat
*** Truth: We all keep secrets.  Name one secret you are keeping now.
*** Dare: Choose one player.  Tell them a secret about one other player in the room.  Ask them not to repeat it.
* Difficulty: 8
** Title: Personal Copies
*** Dare: Make a printout or photocopy of your ass.  Post it on the nearest window for the duration of the game.
*** Truth: What is your actual weight, age and measurements.
** Title: Hard to Reach Places
*** Truth: When was the last time you went somewhere public without wearing underwear?  What did it feel like?
*** Dare: Remove your underwear.  Wear a skirt, dress or long shirt (whatever is available).  Place an item high on a shelf.
*** Tags: nudity,mature content
** Title: Chug Chug
*** Truth: What was the worst throwing up experience you've ever had?
*** Dare: Drink the entirety of a carbonated 12 ounce beverage.
*** Tags: messy
** Title: It's All Presentation
*** Truth: What is the kinkiest thing you've ever done with a piece of food?
*** Dare: Choose 3 pieces of food.  Have another player place them on three different parts of their body and eat them off.
*** Tags: contact,mature content,messy
* Difficulty: 9
** Title: Hairy Palms
*** Truth: When was the first time you masturbated?  What did you do?  Did it work?
*** Dare: Have other players create an improvised masturbatory aid.  Strip to your underwear and use it for 30 seconds to sexy music.
*** Tags: nudity,exhibitionism,mature content
** Title: Yes Yes a spanking
*** Truth: Do you enjoy being spanked?  If yes, how hard?  If no, have you tried it?
*** Dare: Each player gets to line up to give you one spanking.  Count them off.
*** Tags: exhibitionism,mature content,contact
** Title: Don't Speak with your Mouth Full
*** Truth: What is the most unusual oral thing you've ever been asked to do?  Did you do it?
*** Dare: Felatiate one body part of other player.  You choose which part (they have to agree).
*** Tags: exhibitionism,mature content,contact,body fluids
** Title: All Tied Up
*** Truth: How does bondage make you feel?  What have you tried?
*** Dare: Find something to make a blindfold and tie your hands behind your back.  Each player gets to whisper something to you in turn.
*** Tags: exhibitionism,mature content,contact
* Difficulty: 10
** Title: Be Careful What You Wish For
*** Truth: Close your eyes and spend the next 2 minutes describing a sexual fantasy involving everyone in the room.  Go.
*** Dare: Choose up to 3 players.  Describe one act they must perform for 2 minutes.  They must do it.  Go.
*** Tags: exhibitionism,mature content,contact
** Title: Your Wish is My Command
*** Truth: Choose the player in the circle you are most attracted to.  Tell them what you would let them do to you behind closed doors.  Tonight.
*** Dare: Have each player write down their name on a piece of paper.  Have them write down one sexy act on another.  Chose one from each pile.  Do it.
*** Tags: exhibitionism,mature content,contact
** Title: Squeeky Wheel
*** Truth: What is something you've always wanted to be able to do, but have never had anyone willing to do it with you?  Be explicit.
*** Dare: Call up your boss and ask for a raise, Call up a teacher and ask for a better grade, or ask a significant other for a sexual favor you've never asked for.
** Title: The Road Less Traveled By
*** Truth: What is the one romantic choice you most regret.  Would you do it differently if you had a chance?
*** Dare: Write a love letter to someone who got away.  If you still have contact info for them, send it.
*** Tags: internet


